<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR1' => true,
        '@PSR2' => true,
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'linebreak_after_opening_tag' => true,
        'no_superfluous_phpdoc_tags' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_imports' => true,
        'phpdoc_order' => true,
        'semicolon_after_instruction' => true,
    ])
    ->setFinder(PhpCsFixer\Finder::create()
        ->in(__DIR__)
        ->exclude('config')
        ->exclude('var')
        ->exclude('tests/fixtures')
        ->exclude(['vendor', 'var'])
        // exclude files generated by Symfony Flex recipes
        ->notPath('bin/console')
        ->notPath('bin/phpunit')
        ->notPath('public/index.php')
    )
;
